=== IngridIplinsky/ILS/dominio/exercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="exercicio">
	<xs:complexType>
		<xs:sequence>
			
			<xs:element name="conteudo" type="xs:string"/>
			<xs:element name="idEx" type="xs:string"/>
			<xs:element name="nivel" type="xs:string"/>
			<xs:element name="tipo" type="xs:string"/>
			<xs:element name="preReq" type="xs:string"/>

			<xs:element name="enunciado" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					
    					<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					
						<xs:element name="enum" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item">
										<xs:complexType>
											<xs:sequence>
												<xs:attribute name="id" type="xs:string"/>
											<xs:sequence>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      				</xs:sequence>
				</xs:complexType>
      		</xs:element>
			
			<xs:element name="alternativa" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					<xs:attribute name="id" type="xs:string" minOccurs="0"/>
						<xs:element name="valor" type="xs:boolean" minOccurs="0"/>
      					
      					<xs:element name="texto" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string"/>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      					<xs:element name="codigo" type="xs:string" minOccurs="0"/>
    				</xs:sequence>
  				</xs:complexType>
			</xs:element>

			<xs:element name="texto" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="codigo" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="resposta">
  				<xs:complexType>
    				<xs:sequence>
						<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					</xs:sequence>
  				</xs:complexType>
			</xs:element>	
						
		</xs:sequence>
  	</xs:complexType>
</xs:element>
</xs:schema>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/alocDin/exercicios/ad008.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<conteudo>alocDin</conteudo>
		<idEx>ad008</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req>vetor</req>
		</preReq>

		<enunciado> 
			<texto>Marque a alternativa correta para se alocar um vetor inteiro vet de 500 posições na linguagem C:</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="yes">vet = (int*) malloc (sizeof(int))</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">(int*) malloc (sizeof(int))</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">malloc (500*sizeof(int))</codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="yes">malloc (500*sizeof(int))</codigo>	
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio2/alocDin/exercicios/ad002.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> alocacao dinamica </conteudo>	
		<idEx> ad002 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> </preReq>
		
		<enunciado> 
			<texto>
			Em alguns sistemas computacionais, o gasto de memória é decisivo na produção de um software. 
		    Para não haver desperdício de memória:
		    </texto> 
		</enunciado>

		<alternativa> 
			<texto> Se faz alocação estática, pois se delimita a quantidade de memória que se quer usar.</texto>
		</alternativa>
		
		<alternativa> 
			<texto> Se faz alocação dinâmica, colocando a quantidade de posições da estrutura que se quer utilizar. </texto>
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> Se faz alocação dinâmica, não colocando a quantidade de posições. </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores. </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/vetor/exercicios/v008.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<conteudo>vetor</conteudo>	
		<idEx>v008</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq> </preReq>

		<enunciado> 
			<texto>Dado um vetor A definido com:</texto> 
			<codigo>int A[99];</codigo>
			<texto>como preenchÃª-lo com o valor 30?</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo>afor (int i = 0; i &lt;= 99; i++) A[i] = 30;</codigo>
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo>for  (int i = 0; i &lt; 99; i++)  A[i] = 30;</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo>for (int i = 1; i &lt;= 99; i++)  A[i] = 30;</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo>for (int i = 0; i &lt;= 99; i++){ A[i] = 30; i++;}</codigo>	
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/vetor/exercicios/v010.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>vetor</conteudo>	
		<idEx>v010</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req></req>
		</preReq>

		<enunciado> 
			<texto>Dada uma sequência de n números, marque a alternativa que imprime esta na ordem inversa à da leitura.</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="yes">
				for (i = 0; i &lt; n; i++) 
					scanf(&quot;%d&quot;, &amp;v[i]);
						for (i = n-1; i &gt;= 0; i--)
							printf(&quot;%d&quot;, v[i]); 
			</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">
				for (i = 1; i &lt; n; i++)
					scanf(&quot;%d&quot;, &amp;v[i]);
						for (i = n-1; i &gt;= 1; i--)
							printf(&quot;%d&quot;, v[i]);
			</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes"> 
				for (i = 1; i &lt; n; i++)
					scanf(&quot;%d&quot;, &amp;v[i]);
						for (i = n; i &gt;= 1; i--)
							printf(&quot;%d&quot;, v[i]);
			</codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="yes"> 
				for (i = 1; i &lt; n; i++)
					scanf(&quot;%d&quot;, &amp;v[i]);
						for (i = n; i &gt; 1; i--)
							printf(&quot;%d&quot;, v[i]);
			</codigo>	
		</alternativa>
		

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/IntroducaoProgramacao/vetor/exercicios/v003.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">

		<disciplina>GSI002</disciplina>
		<conteudo>vetor</conteudo>	
		<idEx>v003</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req></req>
		</preReq>

		<enunciado> 
			<texto>Qual código a seguir percorre o vetor de caracteres de 4 posições, imprimindo cada item:</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="yes">for(i = 0, i &lt;= 4, i++)  printf(%d, vetor[i]);</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">for(i = 0; i &lt; 4, i++)  printf(&quot;%d&quot;,vetor[i]);</codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="yes">for(i = 0; i &lt; 4, i++)  printf(%c,vetor[i]);</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<texto>Nenhuma das anteriores.</texto>
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/alocDin/exercicios/ad010.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> alocacao dinamica </conteudo>	
		<idEx> ad010 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> </preReq>

		<enunciado>
			<codigo>  
			int Func(vet) 
			{ 
				vet = (int*) malloc (sizeof(int)); 
				if(vet == NULL) 
					return 0 
				else 
					return 1 
			}
			</codigo>
			<texto> O que o c√≥digo faz ? </texto>
		</enunciado>

		<alternativa> 
			<texto> aloca um vetor e retorna seu valor </texto>
		</alternativa>
		
		<alternativa> 
			<texto>  aloca e depois limpa a memoria </texto>	
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> aloca e verifica se deu certo </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores </texto>	
		</alternativa>
		

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/vetor/exercicios/v003.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">

		<conteudo>vetor</conteudo>	
		<idEx>v003</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>

		<enunciado> 
			<texto> Qual código a seguir percorre o vetor de caracteres de 4 posições, imprimindo cada item: </texto> 
		</enunciado>

		<alternativa> 
			<codigo> for(i = 0, i &lt;= 4, i++)  printf(%d, vetor[i]); </codigo>
		</alternativa>
		
		<alternativa> 
			<codigo> for(i = 0; i &lt; 4, i++)  printf(&quot;%d&quot;,vetor[i]); </codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo> for(i = 0; i &lt; 4, i++)  printf(%c,vetor[i]); </codigo>	
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores. </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio2/fila/exercicios/f002.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> fila </conteudo>	
		<idEx> f002 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> </preReq>
		
		<enunciado valor="true"> 
			<texto> Como uma fila pode ser representada em C? </texto>
		</enunciado>

		<alternativa> 
			<texto> Vetor, Lista (mudando as propriedades) </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Struct, pilha </texto>
		</alternativa>
		
		<alternativa> 
			<texto> SÃ³ vetor </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>
