=== IngridIplinsky/ILS/dominio/exercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="exercicio">
	<xs:complexType>
		<xs:sequence>
			
			<xs:element name="conteudo" type="xs:string"/>
			<xs:element name="idEx" type="xs:string"/>
			<xs:element name="nivel" type="xs:string"/>
			<xs:element name="tipo" type="xs:string"/>
			<xs:element name="preReq" type="xs:string"/>

			<xs:element name="enunciado" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					
    					<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					
						<xs:element name="enum" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item">
										<xs:complexType>
											<xs:sequence>
												<xs:attribute name="id" type="xs:string"/>
											<xs:sequence>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      				</xs:sequence>
				</xs:complexType>
      		</xs:element>
			
			<xs:element name="alternativa" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					<xs:attribute name="id" type="xs:string" minOccurs="0"/>
						<xs:element name="valor" type="xs:boolean" minOccurs="0"/>
      					
      					<xs:element name="texto" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string"/>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      					<xs:element name="codigo" type="xs:string" minOccurs="0"/>
    				</xs:sequence>
  				</xs:complexType>
			</xs:element>

			<xs:element name="texto" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="codigo" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="resposta">
  				<xs:complexType>
    				<xs:sequence>
						<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					</xs:sequence>
  				</xs:complexType>
			</xs:element>	
						
		</xs:sequence>
  	</xs:complexType>
</xs:element>
</xs:schema>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/alocDin/exercicios/ad009.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>alocDin</conteudo>
		<idEx>ad009</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req>vetor</req>
		</preReq>

		<enunciado> 
			<texto>Que função em C é capaz de limpar a memória alocada de um vetor V?</texto>
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="yes">alloc(V)</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">malloc(V)</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">sizeof(V)</codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="yes">free(V)</codigo>	
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/vetor/exercicios/v009.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>vetor</conteudo>	
		<idEx>v009</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req></req>
		</preReq>

		<enunciado> 
			<texto>Dado um vetor B definido com:</texto>
			<codigo>int B[20];</codigo>
			<texto>como preenchê-lo com números inteiros 1, 2, 3, ..., 20.</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="yes">for (int i = 0; i &lt;= 20; i++) A[i] = i;</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">for (int i = 0; i &lt; 19; i++) A[i] = i;</codigo>	
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="yes">for (int i = 1; i &lt; 19; i++) A[i] = i;</codigo>	
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="yes">for (int i = 1; i &lt;= 20; i++) A[i-1] = i</codigo>	
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/alocDin/exercicios/ad006.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> alocacao dinamica </conteudo>
		<idEx> ad006 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> </preReq>

		<enunciado> 
			<texto> Dado o código: </texto>
			<codigo> ptr = malloc (sizeof (data)); </codigo>
			<texto> O que a variavel ptr representa? </texto>
		</enunciado>

		<alternativa> 
			<texto> Devolve o endereço</texto>
		</alternativa>
		
		<alternativa> 
			<texto> Devolve um valor qualquer </texto>
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> Devolve NULL </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Devolve lixo </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/lista/exercicios/l011.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<conteudo>lista</conteudo>	
		<idEx>l011</idEx>
		<nivel>medio</nivel>
		<tipo>programacao</tipo>
		<preReq>
			<req>alocDin</req>
		</preReq>

		<enunciado> 
			<texto> 
				Considere estruturas de listas encadeadas que armazenam valores inteiros.
				O tipo que representa um nó da lista é dado por:
			 </texto> 
			<codigo highlight="yes">
				struct lista {
					int info; 
					struct lista *prox;
				};
			typedef struct lista Lista;
			</codigo>  
			<texto> 
				Implemente uma função que receba um vetor de valores inteiros com n elementos e construa uma lista 
				encadeada armazenando os elementos do vetor nos nós da lista. Assim, se for recebido o vetor
			</texto> 
			<codigo highlight="yes">
				v[5] = {3, 8, 1, 7, 2}
			</codigo> 
			<texto> 
				, a funcao deve retornar uma nova lista cujo primeiro nó tem a informação 3, o segundo a informação 8,
				e assim por diante. Se o vetor tiver zero elementos, a função deve ter como valor de retorno uma lista vazia.
				O protótipo da função é dado por:
			</texto> 
			<codigo highlight="yes">
				Lista* constroi (int n, int* v);
			</codigo>
		</enunciado>
		
		<resposta>
			<codigo>
				Lista* constroi (int n, int* v)
				{
					Lista* p;   /* variável auxiliar para percorrer a lista */
					Lista* q;   /* variável auxiliar para criar a nova lista */
					int i;
					q = NULL;
					for(i=n-1; i>=0; i--)   
					{ 
						p = (Lista*) malloc(sizeof(Lista));
						p->prox = q;
						p->info = v[i]; 
						q = p;
					}
					return q;
				}
			</codigo>
	 	</resposta>

		<entradaCodigo />

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/lista/exercicios/l001.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
	
	<conteudo>lista</conteudo>	
	<idEx>l001</idEx>
	<nivel>facil</nivel>
	<tipo>me</tipo>
	<preReq>
		<req></req>
	</preReq>

	<enunciado> 
		<texto>Quais são os tipos de lista?</texto>
	</enunciado>
	
	<resposta> </resposta>

	<alternativa valor="false"> 
		<texto> encadeada reversa, duplamente encadeada, cíclica e estática </texto>
	</alternativa>
		
	<alternativa valor="false"> 
		<texto> encadeada reversa, encadeada transversa, circular e estática  </texto>
	</alternativa>
		
	<alternativa valor="true"> 
		<texto> encadeada simples, duplamente encadeada, circular e estática </texto>
	</alternativa>
		
	<alternativa valor="false"> 
		<texto> Nenhuma das alternativas anteriores. </texto>
	</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/lista/exercicios/l002.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>lista</conteudo>	
		<idEx>l002</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req>alocDin</req>
		</preReq>
		
		<enunciado> 
			<texto>Como inicializar uma lista?</texto> 
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<codigo highlight="no">Lista %L</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="no">Lista &amp;L</codigo>
		</alternativa>
		
		<alternativa valor="true"> 
			<codigo highlight="no">Lista *L</codigo>
		</alternativa>
		
		<alternativa valor="false"> 
			<codigo highlight="no">Lista #L</codigo>
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/lista/exercicios/l006.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<conteudo>lista</conteudo>	
		<idEx>l006</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>alocacao dinamica, vetor, fila, pilha, metodos pesquisa</preReq>

		<enunciado> 
			<texto>A seguinte estrutura é definida em C:</texto>
			<codigo>struct n{ int info; struct node *next;};</codigo>
        	<texto>O que esta estrutura representa?</texto>
	 	</enunciado>
	 	
	 	<resposta> </resposta>

		<alternativa valor="false"> 
			<texto>Um nó para representar uma lista estática</texto>
		</alternativa>
		
		<alternativa valor="false"> 
			<texto>Um nó para representar uma lista dinâmica</texto>	
		</alternativa>
		
		<alternativa valor="false"> 
			<texto>O maior elemento de uma lista e seu próximo</texto>	
		</alternativa>
		
		<alternativa valor="true"> 
			<texto>Remove o primeiro elemento</texto>	
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/fila/exercicios/f005.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> fila </conteudo>	
		<idEx> f005 </idEx>
		<nivel> facil </nivel>
		<tipo> vf </tipo>
		<preReq> </preReq>

		<enunciado> 
			<texto> Marque v para verdadeiro e f para falso: </texto>
		</enunciado>

		<alternativa valor="true"> 
			<texto> Na fila dinâmica, os elementos são encadeados para garantir a organização. </texto>
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> A fila estática tem um número fixo de elementos, igual o tamanho do vetor. </texto>	
		</alternativa>
		
		<alternativa valor="false"> 
			<texto> Em uma fila estática, os dados removidos também são eliminados do vetor. </texto>
		</alternativa>
		
		<alternativa valor="false"> 
			<texto> Nunca irá ocorrer Overflow em uma fila dinâmica. </texto>
		</alternativa>

</exercicio>
