=== IngridIplinsky/ILS/dominio/exercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="exercicio">
	<xs:complexType>
		<xs:sequence>
			
			<xs:element name="conteudo" type="xs:string"/>
			<xs:element name="idEx" type="xs:string"/>
			<xs:element name="nivel" type="xs:string"/>
			<xs:element name="tipo" type="xs:string"/>
			<xs:element name="preReq" type="xs:string"/>

			<xs:element name="enunciado" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					
    					<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					
						<xs:element name="enum" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item">
										<xs:complexType>
											<xs:sequence>
												<xs:attribute name="id" type="xs:string"/>
											<xs:sequence>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      				</xs:sequence>
				</xs:complexType>
      		</xs:element>
			
			<xs:element name="alternativa" minOccurs="0">
  				<xs:complexType>
    				<xs:sequence>
    					<xs:attribute name="id" type="xs:string" minOccurs="0"/>
						<xs:element name="valor" type="xs:boolean" minOccurs="0"/>
      					
      					<xs:element name="texto" minOccurs="0">
  							<xs:complexType>
    							<xs:sequence>
      								
      								<xs:element name="item" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string"/>
										</xs:complexType>
									</xs:element>
									
								</xs:sequence>
							</xs:complexType>
      					</xs:element>
      					
      					<xs:element name="codigo" type="xs:string" minOccurs="0"/>
    				</xs:sequence>
  				</xs:complexType>
			</xs:element>

			<xs:element name="texto" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="codigo" minOccurs="0">
				<xs:complexType>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="resposta">
  				<xs:complexType>
    				<xs:sequence>
						<xs:element name="texto" type="xs:boolean" minOccurs="0"/>
						<xs:element name="codigo" type="xs:boolean" minOccurs="0"/>
					</xs:sequence>
  				</xs:complexType>
			</xs:element>	
						
		</xs:sequence>
  	</xs:complexType>
</xs:element>
</xs:schema>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/IntroducaoProgramacao/introducao/exercicios/a007.xml
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<conteudo>introducao</conteudo>	
		<idEx>a007</idEx>
		<nivel>facil</nivel>
		<tipo>programacao</tipo>
		<preReq>
			<req></req>
		</preReq>

		<enunciado> 
			<texto> 
				Ler o valor do raio de um círculo e calcular a área do círculo correspondente. 
				A área do círculo é pi * raio2, considere pi = 3.141592.
			</texto> 
		</enunciado>
		
		<resposta>
			<codigo>
				int main(){
					float r;
					float pi = 3.141592;
					float a;
				    printf("Entre com a temperatura em celsius: ");
				    scanf("%f", r); 
				    a = pi * (r*r);
					printf("\nA area do circulo eh: %f", a);
					return 0;
				}
			</codigo>
		</resposta>

		<entradaCodigo />
		

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/fila/exercicios/f010.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> fila </conteudo>	
		<idEx> f010 </idEx>
		<nivel> facil </nivel>
		<tipo> aa </tipo>
		<preReq> </preReq>

		<enunciado> 
			<texto> O protótipo de uma função em C, contida em uma biblioteca de fila, segue abaixo: </texto>
			<codigo>void func(Fila* f, float v);</codigo>
         	<texto>O que esta função pode representar em uma fila?</texto>
			<enum> 
				<item id="1">Insercao</item>
				<item id="2">Criacao </item>
				<item id="3">Remocao </item>
			</enum>
			<texto> Analise as afirmações e marque a alternativa correta: </texto>
		</enunciado>

		<alternativa> 
			<texto>  As afirmações <item id="1" /> e <item id="2" /> são corretas. </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Criação da Fila </texto>	
		</alternativa>
		
		<alternativa val="true"> 
			<texto> As afirmações <item id="1" /> e <item id="3" /> são corretas. </texto>	
		</alternativa>
		
		<alternativa> 
			<texto> A primeira e terceira alternativas estão corretas. </texto>	
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores </texto>	
		</alternativa>
		

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/IntroducaoProgramacao/vetor/exercicios/v005.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>GSI002</disciplina>
		<conteudo>vetor</conteudo>	
		<idEx>v005</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>
		<preReq>
			<req></req>
		</preReq>

		<enunciado> 
			<texto>Tenho o seguinte código</texto>
			<codigo highlight="yes">for(i=0; i&lt;5; i++) Vetor[i] = i+2</codigo>
			<texto>O que esse código faz?</texto>
		</enunciado>
		
		<resposta> </resposta>

		<alternativa valor="false"> 
			<texto>Preenche o Vetor com o número 1.</texto>
		</alternativa>
		
		<alternativa valor="false"> 
			<texto>Preenche o Vetor de 1 à 5.</texto>	
		</alternativa>
		
		<alternativa valor="false"> 
			<texto>Preenche o Vetor com número 0.</texto>
		</alternativa>
		
		<alternativa valor="true"> 
			<texto>Nenhuma das alternativas anteriores.</texto>
		</alternativa>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio2/fila/exercicios/f006.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo> fila </conteudo>	
		<idEx> f006 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> </preReq>

		<enunciado> 
			<texto> Como é representada uma Fila estática? </texto>
	 	</enunciado>

		<alternativa> 
			<texto> Usando apenas uma estrutura (struct) </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Usando matriz </texto>	
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> Usando vetor </texto>	
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores </texto>	
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio2/lista/exercicios/l004.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">

		<conteudo> lista </conteudo>	
		<idEx> l004 </idEx>
		<nivel> facil </nivel>
		<tipo> me </tipo>
		<preReq> alocacao dinamica, vetor, fila, pilha, metodos pesquisa </preReq>

		<enunciado> 
			<texto> Quais são as informações essenciais para reproduzir uma lista encadeada? </texto>  
		</enunciado>

		<alternativa> 
			<texto> tamanho da lista e elemento do meio </texto>
		</alternativa>
		
		<alternativa> 
			<texto> o primeiro e último elementos </texto>	
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> o primeiro elemento e o próximo </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Nenhuma das anteriores. </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/vetor/exercicios/v005.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/home/eduardo/Desktop/dominio/src/dominio/exercicio.xsd">
		
		<conteudo>vetor</conteudo>	
		<idEx>v005</idEx>
		<nivel>facil</nivel>
		<tipo>me</tipo>

		<enunciado> 
			<texto> Tenho o seguinte código: </texto> 
			<codigo>for(i=0; i&lt;5; i++) Vetor[i] = i+2 </codigo> 
			<texto> O que esse código faz? </texto> 
                        
		</enunciado>

		<alternativa> 
			<texto> Preenche o Vetor com o número 1. </texto>
		</alternativa>
		
		<alternativa> 
			<texto> Preenche o Vetor de 1 à 5. </texto>	
		</alternativa>
		
		<alternativa> 
			<texto> Preenche o Vetor com número 0. </texto>
		</alternativa>
		
		<alternativa valor="true"> 
			<texto> Nenhuma das alternativas anteriores. </texto>
		</alternativa>

		<resposta> </resposta>

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/lista/exercicios/l012.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>lista</conteudo>	
		<idEx>l012</idEx>
		<nivel>medio</nivel>
		<tipo>programacao</tipo>
		<preReq>
			<req>alocDin</req>
		</preReq>

		<enunciado> 
			<texto> 
				Considere a implementação de uma lista encadeada para armazenar números reais dada pelo tipo abaixo:
			 </texto> 
			<codigo highlight="yes">
				struct lista {
					float info; 
					struct lista *prox;
				};
			typedef struct lista Lista;
			</codigo>  
			<texto> 
				Implemente uma função que, dados uma lista encadeada e um número inteiro não negativo n, remova
				da lista seus n primeiros nós e a lista resultante. Caso n seja maior do que o comprimento da lista,
				todos os seus elementos devem ser removidos e o resultado da função deve ser uma lista vazia. Esta função
				deve obedecer o seguinte protótipo:
			</texto> 
			<codigo highlight="yes">
				Lista* retira_prefixo (Lista* l, int n);
			</codigo> 
		</enunciado>
		
		<resposta>
			<codigo>
				Lista* retira_prefixo (Lista* l, int n)
				{
					Lista* p; /* variável auxiliar para percorrer a lista */
					Lista* q; /* variável auxiliar */
					int m = 1;
					p = l;
					while(p != NULL &amp;&amp; m &lt;= n)
					{ 
						m = m+1;
						q = p-&gt;prox;
						free(p);
						p = q;
					}
					return p;

				}
			</codigo>
	 	</resposta>

		<entradaCodigo />

</exercicio>

=== IngridIplinsky/ILS/src/ils/models/dominio/Cursos/EstruturasDados/lista/exercicios/l014.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercicio
 xmlns="exercicio"
 xmlns:xsi="exercicio"
 xsi:schemaLocation="/src/dominio/exercicio.xsd">
		
		<disciplina>INF41</disciplina>
		<conteudo>lista</conteudo>	
		<idEx>l014</idEx>
		<nivel>dificil</nivel>
		<tipo>programacao</tipo>
		<preReq>
			<req>alocDin</req>
			<req>metOrd</req>
		</preReq>

		<enunciado> 
			<texto> 
				Considere uma lista simplesmente encadeada que armazena os seguintes dados de alunos de uma disciplina:
			 </texto> 
			 <enum>
			 	<item id="1"> Número de matrícula: número inteiro </item>
			 	<item id="2"> Nome: até 80 caracteres </item>
			 	<item id="3"> Nome na disciplina: número de ponto flutuante </item>
			 </enum>
			 <texto> 
				Considerando que a estrutura que representa um nó de lista é dado por:
			</texto>
			<codigo highlight="yes">
				struct lista {
					int matricula;
					char nome[81];
					float media;
					struct lista* prox;
				}
				typedef struct lista Lista;
			</codigo>   
			<texto> 
				Implemente uma função que insira, em ordem crescente de número de matrícula, os dados de um novo aluno na lista.
				Esta função deve obedecer o seguinte protótipo, retornando o ponteiro para o primeiro elemento:
			</texto> 
			<codigo highlight="yes">
				Lista* ins_ordenado (Lista* l, int mat, char* nome, float nota);
			</codigo>
		</enunciado>
		
		<resposta>
			<codigo>
				Lista* ins_ordenado(Lista* L, int mat, char* nome, float nota) 
				{
					Lista* p = L;
					Lista ant = NULL;
					Lista* novo = (Lista*)malloc(sizeof(Lista));
					novo -&gt;mat = mat;
					strcpy(novo-&gt;nome, nome);
					novo-&gt;media = nota;
					novo-&gt;prox = NULL;
					if (p==NULL) 
						return novo;
					while ((p!=NULL) &amp;&amp; (novo-&gt;mat &gt; p-&gt;mat))
					{ 
						ant = p; p = p-&gt;prox;
					}
					if (ant == NULL) {
					novo-&gt;prox = p; 
					return novo;
					}
					novo -&gt;prox = ant-&gt;prox;
					ant-&gt;prox = novo;
					return L;
				}
				
			</codigo>
	 	</resposta>

		<entradaCodigo />

</exercicio>
